### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by vietlhsa** [rajatrawal/quiz-app-django#1]
I run "python manage.py runserver" and Open web browser and explore the project locally at http://localhost:8000/ then it show "A server error occurred.  Please contact the administrator." and in the terminal show error "django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty." How to fix it?

**Comment by rajatrawal** [comment]
https://www.educative.io/answers/how-to-generate-a-django-secretkey


Please refer to the above doc to create a new secret key and paste it into settings.py file
